name: apps
channels:
- conda-forge
- defaults
dependencies:
- numpy
- scipy
- matplotlib
- rasterio
- pandas
- shapely
- h5py
- gdal
- python>=3.5
- pytest
- pytest-cov
- ipython
- jupyter
- cartopy
- fiona
- pycrypto
- paramiko
- obspy
- xlrd
- xlwt
- openpyxl
- xlsxwriter
- beautifulsoup4
- impactutils
- libcomcat
- mapio
